#!/bin/bash

echo "=== Installing Tauri System Dependencies ==="
echo ""
echo "Tauri requires the following system libraries to build on Linux:"
echo ""
echo "Run this command to install them:"
echo ""
echo "sudo apt update && sudo apt install -y \\"
echo "  libwebkit2gtk-4.0-dev \\"
echo "  build-essential \\"
echo "  curl \\"
echo "  wget \\"
echo "  file \\"
echo "  libxdo-dev \\"
echo "  libssl-dev \\"
echo "  libgtk-3-dev \\"
echo "  libayatana-appindicator3-dev \\"
echo "  librsvg2-dev"
echo ""
echo "After installing these dependencies, run ./build-tauri.sh again."