name: Simple Tauri Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-build:
    strategy:
      matrix:
        platform: [windows-latest]
    
    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build web assets
        run: npm run build
        
      - name: Verify dist folder
        run: |
          echo "Contents of dist folder:"
          dir dist
        shell: cmd
        
      - name: Try simple Tauri build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --verbose