name: Build Portable Windows Executable

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-portable-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract portable executable from NSIS
        run: |
          mkdir -p dist\windows-portable
          # The NSIS installer contains the portable exe
          copy src-tauri\target\release\bundle\nsis\*.exe dist\windows-portable\
          dir dist\windows-portable\
          
      - name: Upload portable executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-portable
          path: dist/windows-portable/WebSQL.exe
          if-no-files-found: error